version: 2

aliases:
  - &workspace_root ~/repo

  - &container_config
    docker:
      - image: cimg/node:18.19.0
    working_directory: *workspace_root

  - &repo_cache_key v1-repo-{{ .Branch }}-{{ .Revision }}

  - &restore_repo
    restore_cache:
      keys:
        - *repo_cache_key

  - &deps_cache_key >-
    v2-deps
    {{ checksum ".circleci/config.yml" }}
    {{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

  - &restore_deps
    restore_cache:
      keys:
        - *deps_cache_key

jobs:
  build:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: *repo_cache_key
          paths:
            - .
      - *restore_deps
      - run:
          name: Install deps
          command: |
            set -exu
            npm ci
      - save_cache:
          key: *deps_cache_key
          paths:
            - ~/.npm
      - run: npm test
